default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  database: mctsagsh_development
  username: root
  password: password
  host: db

test:
  <<: *default
  database: mctsagsh_test
  username: root
  password: password
  host: db

production:
  <<: *default
  database: mctsagsh_production
